backend:
  name: git-gateway
  # name: github
  # repo: flaviolazzarini/Travel-Blog

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entries"
    label: "Entries"
    folder: "entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Place", name: "map", widget: "map"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "TravelBlog", name: "travelBlog", widget: "relation", collection: "posts", searchFields: "title", valueField: "title", displayFields: "title"}
      - {label: "Body", name: "body", widget: "markdown"}